# Generated by Django 3.1.3 on 2020-11-10 22:44

import PaginaWebApp.rutificador
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('rut', models.TextField(max_length=12, validators=[PaginaWebApp.rutificador.validate_rutificador])),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTarjeta', models.TextField(max_length=12)),
                ('saldoDisponible', models.IntegerField()),
                ('rut', models.TextField(max_length=12, validators=[PaginaWebApp.rutificador.validate_rutificador])),
                ('clave', models.TextField(max_length=4)),
            ],
        ),
    ]
